import styles from "./page.module.css"
import Link from "next/link"

export const metadata = {
  title: "Privacy Policy — House of Michaels",
  description: "Privacy Policy for House of Michaels membership platform.",
}

const LAST_UPDATED = "May 31, 2026"
const CONTACT_EMAIL = "privacy@houseofmichaels.com"
const OWNER_EMAIL = "mikeokpechi@gmail.com"
const APP_NAME = "House of Michaels"
const WEBSITE = "https://houseofmichaels.com"

export default function PrivacyPage() {
  return (
    <div className={styles.page}>
      <div className={styles.inner}>
        <Link href="/" className={styles.back}>← House of Michaels</Link>

        <div className={styles.header}>
          <p className={styles.eyebrow}>Legal</p>
          <h1 className={styles.title}>Privacy Policy</h1>
          <p className={styles.meta}>Last updated: {LAST_UPDATED}</p>
        </div>

        <div className={styles.body}>

          <section className={styles.section}>
            <h2>1. Introduction</h2>
            <p>
              House of Michaels ("we," "our," or "us") operates the {APP_NAME} platform,
              including the website at {WEBSITE} and any associated mobile applications
              (collectively, the "Service"). This Privacy Policy explains how we collect,
              use, disclose, and safeguard your information when you use our Service.
            </p>
            <p>
              By using the Service, you agree to the collection and use of information in
              accordance with this policy. If you do not agree with the terms of this
              Privacy Policy, please discontinue use of the Service immediately.
            </p>
          </section>

          <section className={styles.section}>
            <h2>2. Information We Collect</h2>

            <h3>2.1 Information You Provide Directly</h3>
            <ul>
              <li><strong>Name and email address</strong> — provided when you authenticate via Google or LinkedIn OAuth.</li>
              <li><strong>Profile information</strong> — city, country, industry, bio, description of what you are building, skills, and goals — entered voluntarily during profile setup.</li>
              <li><strong>Profile photo URL</strong> — an optional external URL you provide pointing to a profile image hosted on a third-party platform. We store the URL only; we do not download, process, analyse, or perform any face detection on the image.</li>
              <li><strong>Posts and responses</strong> — content you create on the Collab Board, Help Me board, and weekly pod check-ins.</li>
              <li><strong>Messages</strong> — content you submit via the "Message the Owner" feature.</li>
            </ul>

            <h3>2.2 Information Collected Automatically</h3>
            <ul>
              <li><strong>Authentication tokens</strong> — short-lived session tokens (JWT) generated by NextAuth to maintain your login session. These are stored in cookies and expire automatically.</li>
              <li><strong>Referral codes</strong> — if you arrived via a referral link, we record the referral code in a cookie (7-day expiry) to credit the referring member.</li>
            </ul>

            <h3>2.3 Information We Do NOT Collect</h3>
            <p>
              We explicitly do <strong>not</strong> collect any of the following:
            </p>
            <ul>
              <li><strong>Face data of any kind</strong> — the Service does not use Face ID, facial recognition, face scanning, facial mapping, face detection, or any biometric face-related technology. We do not access the device camera for facial data. We do not process profile photo images to extract facial characteristics or biometric identifiers. No face data is collected, stored, transmitted, or shared.</li>
              <li>Health or medical data</li>
              <li>Location data (precise or coarse)</li>
              <li>Contacts, calendar, or device sensors</li>
              <li>Browsing history outside our Service</li>
              <li>Device identifiers beyond what is strictly required for session management</li>
              <li>Payment card numbers or full payment details (all payment processing is handled directly by Stripe)</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2>3. How We Collect Information</h2>
            <p>We collect information through the following methods:</p>
            <ul>
              <li><strong>OAuth authentication</strong> — when you sign in with Google or LinkedIn, those services share your name, email address, and profile photo URL with us via the OAuth 2.0 / OpenID Connect protocol. We do not receive or store your Google or LinkedIn password.</li>
              <li><strong>Forms and inputs</strong> — when you complete your profile, post to the community boards, or submit a check-in, the information you type is saved to our database.</li>
              <li><strong>Cookies</strong> — we use a session cookie to keep you logged in and an optional referral cookie. We do not use tracking, advertising, or analytics cookies.</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2>4. Face Data</h2>
            <p>
              <strong>The {APP_NAME} Service does not collect, use, process, store, transmit,
              or share face data of any kind.</strong>
            </p>
            <p>
              Members may optionally provide a URL that links to a profile photo hosted
              on an external service (such as LinkedIn or a personal website). We store
              this URL as a text string in our database. We do not:
            </p>
            <ul>
              <li>Download or copy the image referenced by the URL.</li>
              <li>Analyse the image for facial features, facial recognition, or any biometric processing.</li>
              <li>Use Apple&apos;s Vision framework, ARKit, or any other face detection or recognition technology.</li>
              <li>Request camera access for facial scanning or any other purpose.</li>
            </ul>
            <p>
              Profile photos displayed within the Service are loaded directly from
              the external URL provided by the member; no image processing is performed
              by our servers.
            </p>
          </section>

          <section className={styles.section}>
            <h2>5. Artificial Intelligence and Third-Party AI Services</h2>
            <p>
              <strong>The {APP_NAME} Service does not use, integrate, or send user data
              to any third-party artificial intelligence (AI) service.</strong>
            </p>
            <p>
              All features of the Service — including member authentication, payment
              processing, community boards, pod check-ins, and the referral system — are
              built on standard software infrastructure and do not involve AI processing
              of user data. No personal data is transmitted to any large language model
              (LLM), machine learning API, or AI-based analytics service.
            </p>
            <p>
              Authentication via Google Sign-In and LinkedIn Sign-In uses standard OAuth
              2.0 and OpenID Connect protocols. These are authentication standards, not
              AI services.
            </p>
          </section>

          <section className={styles.section}>
            <h2>6. How We Use Your Information</h2>
            <p>We use the information we collect to:</p>
            <ul>
              <li>Authenticate your identity and maintain your login session.</li>
              <li>Display your profile in the member directory (visible to other members only).</li>
              <li>Assign you to an accountability pod and display your check-ins to pod members.</li>
              <li>Show your posts on the Collab Board and Help Me board to other members.</li>
              <li>Track referral credit and compute your membership tier level.</li>
              <li>Send you email notifications when another member responds to your post (using Resend email service).</li>
              <li>Forward your "Message the Owner" submissions to the founder&apos;s email address.</li>
              <li>Process your one-time lifetime membership payment (via Stripe).</li>
              <li>Comply with applicable laws and legal obligations.</li>
            </ul>
            <p>We do <strong>not</strong> use your information for advertising, profiling, or sale to third parties.</p>
          </section>

          <section className={styles.section}>
            <h2>7. Third-Party Services</h2>
            <p>
              We share data with the following third-party services solely to operate the Service:
            </p>

            <table className={styles.table}>
              <thead>
                <tr>
                  <th>Service</th>
                  <th>Purpose</th>
                  <th>Data Shared</th>
                  <th>Privacy Policy</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Google (OAuth)</td>
                  <td>Authentication</td>
                  <td>Name, email, profile photo URL</td>
                  <td>policies.google.com/privacy</td>
                </tr>
                <tr>
                  <td>LinkedIn (OAuth)</td>
                  <td>Authentication</td>
                  <td>Name, email, profile photo URL</td>
                  <td>linkedin.com/legal/privacy-policy</td>
                </tr>
                <tr>
                  <td>Stripe</td>
                  <td>Payment processing</td>
                  <td>Email address, payment details (handled directly by Stripe)</td>
                  <td>stripe.com/privacy</td>
                </tr>
                <tr>
                  <td>Resend</td>
                  <td>Transactional email</td>
                  <td>Email address, name, notification content</td>
                  <td>resend.com/privacy</td>
                </tr>
              </tbody>
            </table>

            <p>
              No user data is sold, rented, or shared with any other third party for
              marketing, advertising, or any other purpose.
            </p>
          </section>

          <section className={styles.section}>
            <h2>8. Payments</h2>
            <p>
              {APP_NAME} charges a one-time lifetime membership fee ($25 for Michael tier
              members; $35 for Inspired by Michael tier members). All payment processing
              is handled exclusively by <strong>Stripe, Inc.</strong> We do not receive,
              store, or have access to your credit card number, CVV, or full payment
              details. Stripe&apos;s handling of your payment data is governed by
              Stripe&apos;s own Privacy Policy at stripe.com/privacy.
            </p>
            <p>
              We store only your email address and a Stripe Checkout Session ID to confirm
              your membership status. We do not store payment card details.
            </p>
          </section>

          <section className={styles.section}>
            <h2>9. Data Retention</h2>
            <ul>
              <li><strong>Member records</strong> — retained for the life of your membership. Since membership is a lifetime purchase, your account record is retained until you request deletion.</li>
              <li><strong>Session cookies</strong> — expire when you log out or within 30 days, whichever comes first.</li>
              <li><strong>Referral cookies</strong> — expire after 7 days.</li>
              <li><strong>Posts and check-ins</strong> — retained while your account is active. Deleted upon account deletion request.</li>
              <li><strong>Face data</strong> — not applicable. No face data is collected or retained.</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2>10. Data Security</h2>
            <p>
              We implement industry-standard security measures to protect your information:
            </p>
            <ul>
              <li>All data is transmitted over HTTPS/TLS encryption.</li>
              <li>Authentication tokens are signed JWT tokens stored in secure, HTTP-only cookies.</li>
              <li>Database access is restricted to authorised application processes only.</li>
              <li>Passwords are never stored — authentication is handled entirely via Google and LinkedIn OAuth.</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2>11. Your Rights</h2>
            <p>
              Depending on your location, you may have the following rights regarding
              your personal data:
            </p>
            <ul>
              <li><strong>Access</strong> — request a copy of the personal data we hold about you.</li>
              <li><strong>Correction</strong> — request correction of inaccurate personal data.</li>
              <li><strong>Deletion</strong> — request deletion of your account and personal data.</li>
              <li><strong>Portability</strong> — request your data in a portable format.</li>
              <li><strong>Objection</strong> — object to certain processing of your personal data.</li>
            </ul>
            <p>
              To exercise any of these rights, email us at{" "}
              <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. We will respond
              within 30 days.
            </p>
          </section>

          <section className={styles.section}>
            <h2>12. Children&apos;s Privacy</h2>
            <p>
              The Service is not directed to individuals under the age of 18. We do not
              knowingly collect personal information from children under 18. If you believe
              we have inadvertently collected information from a child under 18, please
              contact us immediately at {CONTACT_EMAIL} and we will delete it.
            </p>
          </section>

          <section className={styles.section}>
            <h2>13. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify members
              of material changes by posting the updated policy on this page with a revised
              "Last updated" date. Your continued use of the Service after any changes
              constitutes acceptance of the updated policy.
            </p>
          </section>

          <section className={styles.section}>
            <h2>14. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, including questions
              about face data, AI services, or any data handling practice, contact us at:
            </p>
            <div className={styles.contactBlock}>
              <p><strong>{APP_NAME}</strong></p>
              <p>Email: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a></p>
              <p>Owner: <a href={`mailto:${OWNER_EMAIL}`}>{OWNER_EMAIL}</a></p>
              <p>Website: <a href={WEBSITE}>{WEBSITE}</a></p>
            </div>
          </section>

        </div>
      </div>
    </div>
  )
}
